import React, { useState } from 'react';
import { dashboardApi } from '../../../api/dashboardApi';
import { Modal } from '../../../components/ui';
import { useToast } from '../../../context/ToastContext';

const fmtDate = (d) => (d ? new Date(d).toLocaleDateString() : '');

// Turns raw API rows into flat rows shared by the view table and the CSV export
const formatRows = (type, data) => {
  switch (type) {
    case 'leads':
      return data.map(l => ({
        ID: l.leadId, Name: l.name, Company: l.company, Status: l.status,
        Industry: l.industry, State: l.state, District: l.district,
        Owner: l.owner?.name || 'Unassigned', Created: fmtDate(l.createdAt)
      }));
    case 'performance':
      return data.map(p => ({
        Name: p.user?.name, Industry: p.user?.industry, State: p.user?.state,
        Calls: p.calls || 0, Meetings: p.meetings || 0, Conversions: p.conversions || 0, Revenue: p.revenue || 0
      }));
    case 'revenue':
      return data.map(r => ({ Date: r._id, Revenue: r.totalRevenue || 0, Conversions: r.count }));
    case 'attendance':
      return data.map(a => ({
        Staff: a.user?.name, Role: a.user?.role, Date: fmtDate(a.date), Status: a.status,
        WorkPct: `${a.completionPct || 0}%`, LateMins: a.lateLoginMinutes || 0, WFH: a.isWFH ? 'Yes' : 'No'
      }));
    case 'salary':
      return data.map(s => ({
        Staff: s.user?.name, Period: `${s.month}/${s.year}`, Basic: s.baseSalary, WorkingDays: s.workingDays,
        PresentDays: s.presentDays, Deductions: s.deductions || 0, Incentives: s.incentives || 0,
        NetPay: s.netSalary, Status: s.status
      }));
    case 'leaves':
      return data.map(l => ({
        Staff: l.user?.name, Role: l.user?.role, Type: l.type, From: fmtDate(l.fromDate),
        To: fmtDate(l.toDate), Days: l.days, Status: l.status, Reason: l.reason
      }));
    default:
      return data;
  }
};

const Reports = () => {
  const { addToast } = useToast();
  const [loading, setLoading] = useState(null); // `${reportId}:${action}` while a request is in flight
  const [viewing, setViewing] = useState(null); // { card, rows }

  const reportCards = [
    {
      id: 'leads',
      title: 'Lead Reports',
      description: 'Onboarded, meeting, RNR, lost, follow up status breakdown',
      icon: (
        <div className="w-12 h-12 rounded-xl bg-purple/10 flex items-center justify-center text-purple">
          <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M12 20v-6M6 20V10M18 20V4"></path></svg>
        </div>
      )
    },
    {
      id: 'performance',
      title: 'Performance Reports',
      description: 'Work %, calls, meetings, follow ups per staff',
      icon: (
        <div className="w-12 h-12 rounded-xl bg-blue/10 flex items-center justify-center text-blue">
          <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M21.21 15.89A10 10 0 1 1 8 2.83"></path><path d="M22 12A10 10 0 0 0 12 2v10z"></path></svg>
        </div>
      )
    },
    {
      id: 'revenue',
      title: 'Revenue Reports',
      description: 'Revenue generated by team, state, industry',
      icon: (
        <div className="w-12 h-12 rounded-xl bg-amber/10 flex items-center justify-center text-amber">
          <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><circle cx="12" cy="12" r="10"></circle><path d="M16 8h-6a2 2 0 1 0 0 4h4a2 2 0 1 1 0 4H8"></path><path d="M12 18V6"></path></svg>
        </div>
      )
    },
    {
      id: 'attendance',
      title: 'Attendance Report',
      description: 'Present, absent, half-day, late per staff per month',
      icon: (
        <div className="w-12 h-12 rounded-xl bg-orange/10 flex items-center justify-center text-orange">
          <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z"></path></svg>
        </div>
      )
    },
    {
      id: 'salary',
      title: 'Salary Reports',
      description: 'Auto-salary, deductions, incentives, net pay',
      icon: (
        <div className="w-12 h-12 rounded-xl bg-blue-light/50 flex items-center justify-center text-blue">
          <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><rect x="2" y="5" width="20" height="14" rx="2"></rect><line x1="2" y1="10" x2="22" y2="10"></line></svg>
        </div>
      )
    },
    {
      id: 'leaves',
      title: 'Leave Reports',
      description: 'Leave calendar, policies, holiday data by state',
      icon: (
        <div className="w-12 h-12 rounded-xl bg-purple-light/50 flex items-center justify-center text-purple">
          <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect><line x1="16" y1="2" x2="16" y2="6"></line><line x1="8" y1="2" x2="8" y2="6"></line><line x1="3" y1="10" x2="21" y2="10"></line></svg>
        </div>
      )
    }
  ];

  const fetchReport = async (type) => {
    const res = await dashboardApi.getReport(type, { limit: 5000 });
    const data = res.data?.data || res.data || [];
    return formatRows(type, data);
  };

  const downloadCSV = (data, filename) => {
    if (!data || data.length === 0) {
      addToast("No data available for this report", "error");
      return;
    }
    const escape = (val) => {
      if (val === null || val === undefined) return '';
      return typeof val === 'string' ? `"${val.replace(/"/g, '""')}"` : val;
    };
    const headers = Object.keys(data[0]).join(',');
    const rows = data.map(row => Object.values(row).map(escape).join(',')).join('\n');

    const blob = new Blob([headers + "\n" + rows], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${filename}_${new Date().toISOString().split('T')[0]}.csv`;
    link.click();
    URL.revokeObjectURL(url);
    addToast(`${filename} report downloaded`, "success");
  };

  const handleDownload = async (card) => {
    try {
      setLoading(`${card.id}:download`);
      const rows = await fetchReport(card.id);
      if (rows.length === 0) {
        addToast("No records found for this report", "warning");
        return;
      }
      downloadCSV(rows, card.id.toUpperCase());
    } catch (err) {
      addToast("Failed to generate report", "error");
    } finally {
      setLoading(null);
    }
  };

  const handleView = async (card) => {
    try {
      setLoading(`${card.id}:view`);
      const rows = await fetchReport(card.id);
      setViewing({ card, rows });
    } catch (err) {
      addToast("Failed to load report", "error");
    } finally {
      setLoading(null);
    }
  };

  return (
    <div className="animate-in fade-in duration-500 pb-10">
      {/* Page Header */}
      <div className="mb-10">
        <h1 className="text-2xl font-bold text-text-primary">Reports</h1>
      </div>

      {/* Grid of Report Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {reportCards.map((card) => (
          <div
            key={card.id}
            className="bg-white rounded-2xl border border-border p-10 flex flex-col items-center text-center hover:shadow-xl hover:-translate-y-1 transition-all group"
          >
            <div className="mb-6 transform group-hover:scale-110 transition-transform duration-300">
              {card.icon}
            </div>
            <h3 className="text-lg font-bold text-text-primary mb-2 group-hover:text-blue transition-colors">{card.title}</h3>
            <p className="text-sm text-text-muted leading-relaxed max-w-[200px]">
              {card.description}
            </p>
            <div className="mt-8 flex items-center gap-3">
              <button
                className="px-5 py-2 rounded-xl border border-border text-text-primary font-bold text-xs hover:bg-surface2 transition-all disabled:opacity-50"
                disabled={!!loading}
                onClick={() => handleView(card)}
              >
                {loading === `${card.id}:view` ? 'Loading...' : 'View'}
              </button>
              <button
                className="px-5 py-2 rounded-xl bg-[#0f766e] text-white font-bold text-xs shadow-sm hover:shadow-md transition-all disabled:opacity-50"
                disabled={!!loading}
                onClick={() => handleDownload(card)}
              >
                {loading === `${card.id}:download` ? 'Preparing...' : 'Download CSV'}
              </button>
            </div>
          </div>
        ))}
      </div>

      {viewing && (
        <Modal
          title={viewing.card.title}
          subtitle={`${viewing.rows.length} record${viewing.rows.length === 1 ? '' : 's'}`}
          onClose={() => setViewing(null)}
          className="max-w-6xl"
        >
          {viewing.rows.length === 0 ? (
            <div className="py-16 text-center text-sm text-text-muted">No records found for this report</div>
          ) : (
            <>
              <div className="flex justify-end mb-4">
                <button
                  className="px-5 py-2 rounded-xl bg-[#0f766e] text-white font-bold text-xs shadow-sm hover:shadow-md transition-all"
                  onClick={() => downloadCSV(viewing.rows, viewing.card.id.toUpperCase())}
                >
                  Download CSV
                </button>
              </div>
              <div className="overflow-auto max-h-[60vh] border border-border rounded-xl">
                <table className="w-full text-sm">
                  <thead className="bg-surface2 sticky top-0">
                    <tr>
                      {Object.keys(viewing.rows[0]).map(h => (
                        <th key={h} className="text-left px-4 py-3 font-bold text-text-secondary whitespace-nowrap">{h}</th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    {viewing.rows.map((row, i) => (
                      <tr key={i} className="border-t border-border hover:bg-surface2/50">
                        {Object.values(row).map((val, j) => (
                          <td key={j} className="px-4 py-2.5 text-text-primary whitespace-nowrap">{val ?? '—'}</td>
                        ))}
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            </>
          )}
        </Modal>
      )}
    </div>
  );
};

export default Reports;
