import React, { useState } from 'react';
import { dashboardApi } from '../../../api/dashboardApi';
import { Button } from '../../../components/ui';
import { useToast } from '../../../context/ToastContext';

const Reports = () => {
  const { addToast } = useToast();
  const [loading, setLoading] = useState(false);

  const reportCards = [
    {
      id: 'leads',
      title: 'Lead Reports',
      description: 'Onboarded, meeting, RNR, lost, follow up status breakdown',
      icon: (
        <div className="w-12 h-12 rounded-xl bg-purple/10 flex items-center justify-center text-purple">
          <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M12 20v-6M6 20V10M18 20V4"></path></svg>
        </div>
      )
    },
    {
      id: 'performance',
      title: 'Performance Reports',
      description: 'Work %, calls, meetings, follow ups per staff',
      icon: (
        <div className="w-12 h-12 rounded-xl bg-blue/10 flex items-center justify-center text-blue">
          <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M21.21 15.89A10 10 0 1 1 8 2.83"></path><path d="M22 12A10 10 0 0 0 12 2v10z"></path></svg>
        </div>
      )
    },
    {
      id: 'revenue',
      title: 'Revenue Reports',
      description: 'Revenue generated by team, state, industry',
      icon: (
        <div className="w-12 h-12 rounded-xl bg-amber/10 flex items-center justify-center text-amber">
          <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><circle cx="12" cy="12" r="10"></circle><path d="M16 8h-6a2 2 0 1 0 0 4h4a2 2 0 1 1 0 4H8"></path><path d="M12 18V6"></path></svg>
        </div>
      )
    },
    {
      id: 'attendance',
      title: 'Attendance Report',
      description: 'Present, absent, half-day, late per staff per month',
      icon: (
        <div className="w-12 h-12 rounded-xl bg-orange/10 flex items-center justify-center text-orange">
          <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z"></path></svg>
        </div>
      )
    },
    {
      id: 'salary',
      title: 'Salary Reports',
      description: 'Auto-salary, deductions, incentives, net pay',
      icon: (
        <div className="w-12 h-12 rounded-xl bg-blue-light/50 flex items-center justify-center text-blue">
          <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><rect x="2" y="5" width="20" height="14" rx="2"></rect><line x1="2" y1="10" x2="22" y2="10"></line></svg>
        </div>
      )
    },
    {
      id: 'leave',
      title: 'Leave Reports',
      description: 'Leave calendar, policies, holiday data by state',
      icon: (
        <div className="w-12 h-12 rounded-xl bg-purple-light/50 flex items-center justify-center text-purple">
          <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><rect x="3" y="4" width="18" height="18" rx="2" ry="2"></rect><line x1="16" y1="2" x2="16" y2="6"></line><line x1="8" y1="2" x2="8" y2="6"></line><line x1="3" y1="10" x2="21" y2="10"></line></svg>
        </div>
      )
    }
  ];

  const downloadCSV = (data, filename) => {
    if (!data || data.length === 0) {
      addToast("No data available for this report", "error");
      return;
    }
    const headers = Object.keys(data[0]).join(',');
    const rows = data.map(row => 
      Object.values(row).map(val => 
        typeof val === 'string' ? `"${val.replace(/"/g, '""')}"` : val
      ).join(',')
    ).join('\n');
    
    const blob = new Blob([headers + "\n" + rows], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `${filename}_${new Date().toISOString().split('T')[0]}.csv`;
    link.click();
    addToast(`${filename} generated successfully`, "success");
  };

  const generateReport = async (type) => {
    try {
      setLoading(true);
      const res = await dashboardApi.getReport(type === 'leave' ? 'leads' : type); // fallback mapping
      const data = res.data?.data || res.data || [];
      
      if (data.length === 0) {
        addToast("No records found for this criteria", "warning");
        return;
      }

      let formatted = [];
      if (type === 'leads') {
        formatted = data.map(l => ({
          ID: l._id, Name: l.name, Company: l.company, Status: l.status, State: l.state, Owner: l.owner?.name
        }));
      } else if (type === 'performance') {
        formatted = data.map(p => ({
          Name: p.user?.name, Role: p.user?.role, Calls: p.calls, Meetings: p.meetings, Conversions: p.conversions, Revenue: p.revenue
        }));
      } else if (type === 'attendance') {
        formatted = data.map(a => ({
          Staff: a.user?.name, Role: a.user?.role, Status: a.status, WorkPct: `${a.completionPct}%`, Date: new Date(a.date).toLocaleDateString()
        }));
      } else if (type === 'salary') {
        formatted = data.map(s => ({
          Staff: s.user?.name, Basic: s.baseSalary, WorkingDays: s.workingDays, Incentives: s.incentives, NetPay: s.netSalary
        }));
      } else if (type === 'revenue') {
        formatted = data.map(r => ({
          Date: r._id, Revenue: r.totalRevenue, Count: r.count
        }));
      } else {
        formatted = data;
      }

      downloadCSV(formatted, type.toUpperCase());
    } catch (err) {
      addToast("Failed to generate report", "error");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="animate-in fade-in duration-500 pb-10">
      {/* Page Header */}
      <div className="flex justify-between items-center mb-10">
        <div>
          <h1 className="text-2xl font-bold text-text-primary">Reports</h1>
          <p className="text-sm text-text-muted mt-1">All reports · Lead, performance, revenue, attendance, salary</p>
        </div>
        <div className="flex items-center gap-3">
             <div className="relative">
                <input 
                  type="text" 
                  placeholder="Search leads, team, states..." 
                  className="bg-white border border-border rounded-xl pl-10 pr-4 py-2.5 text-sm w-72 focus:ring-2 ring-blue/10 outline-none transition-all"
                />
                <svg className="absolute left-3.5 top-1/2 -translate-y-1/2 text-text-muted" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5"><circle cx="11" cy="11" r="8"></circle><path d="M21 21l-4.35-4.35"></path></svg>
             </div>
             <button className="w-11 h-11 flex items-center justify-center rounded-full bg-white border border-border text-text-secondary hover:bg-surface2 transition-all relative">
                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9"></path><path d="M13.73 21a2 2 0 0 1-3.46 0"></path></svg>
                <span className="absolute top-3 right-3 w-2 h-2 bg-red rounded-full border-2 border-white"></span>
             </button>
             <button className="bg-[#0f766e] text-white px-6 py-2.5 rounded-xl font-bold text-sm shadow-sm hover:shadow-md transition-all">+ Add Lead</button>
             <button className="bg-white border border-border text-text-primary px-6 py-2.5 rounded-xl font-bold text-sm hover:bg-surface2 transition-all">+ State Manager</button>
        </div>
      </div>

      <div className="mb-10">
        <h2 className="text-lg font-bold text-text-primary">Reports</h2>
        <p className="text-xs text-text-muted mt-0.5">Lead reports, performance reports, revenue, attendance & salary exports</p>
      </div>

      {/* Grid of Report Cards */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {reportCards.map((card) => (
          <div 
            key={card.id}
            className="bg-white rounded-2xl border border-border p-10 flex flex-col items-center text-center cursor-pointer hover:shadow-xl hover:-translate-y-1 transition-all group"
            onClick={() => generateReport(card.id)}
          >
            <div className="mb-6 transform group-hover:scale-110 transition-transform duration-300">
              {card.icon}
            </div>
            <h3 className="text-lg font-bold text-text-primary mb-2 group-hover:text-blue transition-colors">{card.title}</h3>
            <p className="text-sm text-text-muted leading-relaxed max-w-[200px]">
              {card.description}
            </p>
            <div className="mt-8 opacity-0 group-hover:opacity-100 transition-opacity">
               <span className="text-blue font-bold text-xs flex items-center gap-2">
                 Generate Master Export
                 <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="3"><polyline points="9 18 15 12 9 6"></polyline></svg>
               </span>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};

export default Reports;
